### PR TITLE
Fix `commonDirectory`, fixes #18

### LINKED ISSUE #18: Extra slashes appearing in `commonDirectory`
While working on #15 I noticed the following:

```haskell
> commonDirectory (compile "foo/*/*.hs")
("foo/",compile "*//*.hs")
```

I was expecting to get `("foo/",compile "*/*.hs")`. Is this a bug?

### PR DESCRIPTION
**Pull request by hdgarrood**
I modified `unseparate` based on the following observations:

- the `Int` argument to the `Dir` and `AnyDir` constructors specifies the number of path separators directly following the `Pattern`
- however, the `AnyDirectory` token represents the string `**/` in a `Pattern`; therefore, we subtract 1 from the argument when unseparating. Otherwise, we end up with one too many separators.
- similarly, I changed the behaviour of `f` so that it produces `n` path separators rather than `n+1` as it was before.

The `unseparate` function is used in one other place, in `matchTypedAndGo` when we encounter an `AnyDir` pattern. The current test suite still passes, but I'm not really sure if that's enough to conclude that I haven't accidentally broken it; do you have any thoughts on that?

### CODE REVIEW

**Comment by hdgarrood** [comment]
It seems the tests are failing because `compile` usually optimises patterns like `[a]` to simply `a`, but not always; for instance:

```haskell
> compile "[a]"
compile "a"

> compile "[.]"
compile "[.]"
```

However, `commonDirectory (compile "[.]/*")` *does* seem to make this optimisation somehow:

```haskell
> commonDirectory (compile "[.]/*")
("./",compile "*")
```

so we end up with `compile "[.]/*" /= compile "./*"`. Perhaps `compile "[.]"` should always end up equal to `compile "."`?

**Comment by hdgarrood** [comment]
This comment in `System.FilePath.Glob.Base` seems to indicate the behaviour of `compile "[.]"` is intended:
```haskell
optimizeCharRange :: Token -> Token
optimizeCharRange (CharRange b_ rs) = fin b_ . go . sortCharRange $ rs
 where
   -- [/] is interesting, it actually matches nothing at all
   -- [.] can be Literalized though, just don't make it into an ExtSeparator so
   --     that it doesn't match a leading dot
   fin True [Left  c] | not (isPathSeparator c) = Literal c
   fin True [Right r] | r == (minBound,maxBound) = NonPathSeparator
   fin b x = CharRange b x
   [...]
```
I'm not really sure what should happen here.

**Comment by Deewiant** [comment]
Yes, the `compile` behaviour is intended. E.g. `man 7 glob`:

> If a filename starts with a '.', this character must be matched explicitly.

Or more clearly in the Tcl manpages of all places, `man n glob`:

> On Unix, as with csh, a “.” at the beginning of a file's name or just after a “/” must be matched explicitly or with a {} construct, unless the `-types hidden` flag is given (since “.” at the beginning of a file's name indicates that it is hidden). On other platforms, files beginning with a “.” are handled no differently to any others, except  the special directories “.” and “..” which must be matched explicitly [...]

...I'd rather not worry about the apparent platform-specificity of this until somebody complains.

The fact that `commonDirectory` turns `[.]` into `.` is a bug, though.

**Comment by hdgarrood** [comment]
I think `commonDirectory` is correct in turning `[.]` into `.`, since it only does this for the first component of the tuple it returns, which is a `FilePath`, not a `Pattern`, and therefore I would expect that to be a literal directory path:

```haskell
> commonDirectory (compile "[.]/*/[.]")
("./",compile "*/[.]")
```

**Comment by hdgarrood** [comment]
(since I would expect to be able to do things like `doesDirectoryExist` and `getDirectoryContents` on it)

**Comment by Deewiant** [comment]
A funny edge case indeed. The pattern `"[.]/*"` cannot match anything, just as the pattern `"[.]"` does not match the `.` directory. So I do think `commonDirectory` is wrong here.

**Comment by hdgarrood** [comment]
Oh, I see! So what should `commonDirectory (compile "[.]/*")` return? Perhaps `("", compile "[.]/*")`?

**Comment by Deewiant** [comment]
I.e. I think the following should be true:

```haskell
commonDirectory (compile "[.]/*") == ("", compile "[.]/*")
```

Maybe `optimize` should optimize any pattern starting with `[.]` to `[.]`, and that could be the canonical black hole pattern that doesn't match anything.

**Comment by hdgarrood** [comment]
Should `compile "[.]foo"` match `.foo`?

**Comment by hdgarrood** [comment]
Oh I see, we're going off `man 7 glob`, not the Tcl one.

**Comment by Deewiant** [comment]
No, the Tcl manpage is in agreement: 'a “.” at the beginning of a file's name or just after a “/” must be matched explicitly or with a {} construct'. `[.]` isn't matching explicitly.

**Comment by hdgarrood** [comment]
Ok, so if I modify `compile` to make it work as it does now, except that if `[.]` occurs at the beginning or directly after a path separator inside a pattern, the whole lot gets optimised to the black-hole pattern `[.]`? and hopefully that should solve this issue?

**Comment by Deewiant** [comment]
Seems like that would indeed be a roundabout way of fixing it, since `commonDirectory (compile "[.]")` does not result in `(".", compile "")` like I thought it might.

But I'd at least like a note in `separate` that it relies on that optimization happening and will otherwise mishandle this situation.

**Comment by hdgarrood** [comment]
Having thought about it a little more, I think `separate` seems to be okay right now:

```haskell
> separate (compile "[.]/*")
[Dir 1 (compile "[.]"),Any (compile "*")] -- this is what I would expect
```

 I think `fromConst` in `commonDirectory` is the cause of the issue, since if we have `Literal '.'` or `LongLiteral 1 "."` that indicates that the . was matched non-explicitly and therefore should not match if it's directly after a path separator or at the beginning, correct? But currently it will simply appear as "." in the `FilePath` component of the returned tuple? So presumably `fromConst` needs to be slightly modified to take care of that? That does seem more sensible than my previous suggestion.

**Comment by Deewiant** [comment]
Good analysis. I think I'd rather amend `splitP` than `fromConst` though but I'm not sure, feel free to tackle it however you see fits best.

**Comment by hdgarrood** [comment]
Yes of course, amending `splitP` did turn out to be easier. I've also added some more test cases to the tests so that if these tests do ever start failing again it won't be nondeterministic.

File: System/FilePath/Glob/Directory.hs [hunk 1]
```diff
@@ -321,3 +321,16 @@ commonDirectory = second unseparate . splitP . separate
...
+   -- "." must be explicitly matched at the start of a pattern or after a path
+   -- separator; this function checks for an implicit match i.e. "[.]".
+   startsWithImplicitExt p =
+      case unPattern p of
+         (Literal '.' : _) ->
+            True
+         (LongLiteral _ l : _) ->
+            case l of
+               ('.':_) -> True
+               _ -> False
```
Comment (Deewiant) [inline System/FilePath/Glob/Directory.hs]: This could be simplified to `LongLiteral _ "." : _ -> True`, but I'd simply leave it out as `optimize` should guarantee that there are no length-1 `LongLiteral`s.

Comment (hdgarrood) [reply System/FilePath/Glob/Directory.hs]: I tried that to start with, but I don't think that will always work; consider:

```haskell
> compile "[.]foo" == Pattern [LongLiteral 4 ".foo"]
True
```

Comment (hdgarrood) [reply System/FilePath/Glob/Directory.hs]: In fact, I should add that as a test case.

Comment (Deewiant) [reply System/FilePath/Glob/Directory.hs]: Ah, true, my mistake.

It might be worth dedicating a new `Token` constructor for `[.]` to make things simpler... but let's just go with this for now.

**Comment by Deewiant** [comment]
Thanks!
