### PR TITLE
Fix ** implicitly matching dot directories when set to False

### LINKED ISSUE #29: ** has inconsistent behavior with hidden directories
`match (compile "haskell/sbu/**/dist/*") "haskell/sbu/.stack-work/dist/test"`
(trying to use `**` to match one level) returns `False` but
`match (compile "haskell/**/dist/*") "haskell/sbu/.stack-work/dist/test"`
(using `**` to match two levels) returns `True`.

Is this a bug or am I missing something about how globs work?

### PR DESCRIPTION
**Pull request by tssund93**
fixes #29 

There was a check for `null xs` that was preventing it from checking directories past the first one.

### CODE REVIEW

**Comment by tssund93** [comment]
I'm pretty new at Haskell so I'm guessing this could be more efficient/easier to read, but basically the problem was that it was using `init` to get the paths to check for dots, so if any of them were hidden besides the last file/directory, even if they were matched explicitly and not by the `**`, it was returning `False`.  Please let me know what I can do to improve this.

File: System/FilePath/Glob/Match.hs [hunk 1]
```diff
@@ -122,14 +124,17 @@ match' o (OpenRange lo hi :xs) path =
...
+   if not (matchDotsImplicitly o)
+      --  **/ shouldn't match foo/.bar, so check that remaining bits don't
+      -- start with .
+      then all (not.isExtSeparator.head) matchedDirs && hasMatch
+      else hasMatch
+ where parts   = pathParts (dropWhile isPathSeparator path)
+       matches = map (match' o xs) parts
+       hasMatch = or matches
+       matchIndex = fromMaybe 0 (elemIndex True matches)
+       (matchedDirs, _) = splitAt matchIndex parts
```
Comment (Deewiant) [inline System/FilePath/Glob/Match.hs]: Since you're not using the other half of the split, this could be simplified using `take`.

File: System/FilePath/Glob/Match.hs [hunk 2]
```diff
@@ -122,14 +124,17 @@ match' o (OpenRange lo hi :xs) path =
...
-match' o again@(AnyDirectory:xs) path =
-   let parts   = pathParts (dropWhile isPathSeparator path)
-       matches = any (match' o xs) parts || any (match' o again) (tail parts)
-    in if null xs && not (matchDotsImplicitly o)
-          --  **/ shouldn't match foo/.bar, so check that remaining bits don't
-          -- start with .
-          then all (not.isExtSeparator.head) (init parts) && matches
-          else matches
+match' o (AnyDirectory:xs) path =
+   if not (matchDotsImplicitly o)
```
Comment (Deewiant) [inline System/FilePath/Glob/Match.hs]: Flipping the then/else cases and removing this `not` would be nicer since it avoids a double negation.

File: System/FilePath/Glob/Match.hs [hunk 3]
```diff
@@ -122,14 +124,17 @@ match' o (OpenRange lo hi :xs) path =
...
+      --  **/ shouldn't match foo/.bar, so check that remaining bits don't
+      -- start with .
```
Comment (Deewiant) [inline System/FilePath/Glob/Match.hs]: This comment is a bit out of date now, since it talks about "remaining bits" but it's now concerning "the directories matched by `**/`" or something along those lines.

File: System/FilePath/Glob/Match.hs [hunk 4]
```diff
@@ -122,14 +124,17 @@ match' o (OpenRange lo hi :xs) path =
...
+      then all (not.isExtSeparator.head) matchedDirs && hasMatch
+      else hasMatch
+ where parts   = pathParts (dropWhile isPathSeparator path)
+       matches = map (match' o xs) parts
+       hasMatch = or matches
+       matchIndex = fromMaybe 0 (elemIndex True matches)
```
Comment (Deewiant) [inline System/FilePath/Glob/Match.hs]: As a tiny performance thing, I think referencing `matches` twice like this is likely to prevent the intermediate list from getting optimized away. I'm not entirely sure though, feel free to examine the compiler output if you want to check. An alternative would be:

```haskell
matchIndex = elemIndex True matches
hasMatch = isJust matchIndex
(matchedDirs, _) = splitAt (fromMaybe 0 matchIndex) parts
```

At that point you could also go about things more directly and get rid of `matches`, using `findIndex` (or whatever it's called) instead of `elemIndex` on top of `map`.

**Comment by tssund93** [comment]
Thanks for the feedback!  I'll take a look at this stuff soon.

**Comment by tssund93** [comment]
I've fixed those issues.  I did have a question about how short-circuiting works in Haskell. Would
```
all (not.isExtSeparator.head) matchedDirs && hasMatch
```
be more efficient if written as
```
hasMatch && all (not.isExtSeparator.head) matchedDirs
```
?

**Comment by Deewiant** [comment]
It would be better like that now, yes. Previously the `isExtSeparator` check had no dependency on any recursive match results, so I wrote it that way around on the assumption that it's much quicker than the recursive calls involved in `hasMatch` (which was called `matches` prior to this PR). Currently you need to compute `matchIndex` for either side of the `&&`, so might as well do the cheaper `hasMatch` check first.

(Whether this actually ends up being more efficient for the user depends on how often `hasMatch` is true or false...)
