### PR TITLE
For GHC 9.2

### LINKED ISSUE #40: Fail with GHC 9.2 and Win32 2.12
A build log is:

```
Failed to build Glob-0.10.1.
Build log (
C:\Users\kazuki\AppData\Roaming\cabal\logs\ghc-9.2.1\Glob-0.10.1-ba443ecd253f1ed0cdc0f5bb4fab897565635639.log
):
Preprocessing library for Glob-0.10.1..
Building library for Glob-0.10.1..
[1 of 7] Compiling System.FilePath.Glob.Utils ( System\FilePath\Glob\Utils.hs, dist\build\System\FilePath\Glob\Utils.o )

System\FilePath\Glob\Utils.hs:29:28: error:
    Module ‘System.Win32.File’ does not export ‘c_GetFileAttributes’
   |
29 | import System.Win32.File  (c_GetFileAttributes, fILE_ATTRIBUTE_DIRECTORY)
   |                            ^^^^^^^^^^^^^^^^^^^
cabal: Failed to build Glob-0.10.1. See the build log above for details.
```

[Win32 2.12's change log](https://github.com/haskell/win32/blob/master/changelog.md#21200-march-2021) says:

> Add export lists to all modules, hiding numerous internal c_ bindings.

### PR DESCRIPTION
**Pull request by kakkun61**
Closes #40

### CODE REVIEW

File: System/FilePath/Glob/Utils.hs [hunk 1]
```diff
@@ -125,6 +127,10 @@ doesDirectoryExist s =
                else return False
 #endif
 
+#if mingw32_HOST_OS
+foreign import ccall unsafe "windows.h GetFileAttributesW" c_GetFileAttributes :: LPCTSTR -> IO FileAttributeOrFlag
```
Comment (Deewiant) [inline System/FilePath/Glob/Utils.hs:131]: I think `ccall` is not always correct: https://github.com/haskell/win32/blob/master/include/windows_cconv.h

**Review by Deewiant — COMMENTED** [review]
Thanks, it's obviously been a while since I've used or even compiled this on Windows...

File: System/FilePath/Glob/Utils.hs (hunk 1 above)
Comment (kakkun61) [reply System/FilePath/Glob/Utils.hs:131]: 32-bit Windows support of GHC is already dropped at GHC 8.6.2, so I think this glob package can drop support for it.

https://www.haskell.org/ghc/download_ghc_8_6_4.html

Comment (Deewiant) [reply System/FilePath/Glob/Utils.hs:131]: travis-ci.org is now dead so the CI here no longer works, but at least at last check Glob still compiled on GHC 8.0: https://github.com/Deewiant/glob/blob/090181e60b448a1ce0e18fe5f5783139f420e721/.travis.yml#L2

Of course this was only tested on Linux, but I'd expect the same to hold for Windows. As such this would be moving the minimum supported GHC version on Windows by a number of releases. It's probably fair enough — I'll let you be the judge of that — but I'd say it's worth an explicit call-out in the eventual release notes, at least.

Comment (kakkun61) [reply System/FilePath/Glob/Utils.hs:134]: I added a piece of code for x86. https://github.com/Deewiant/glob/pull/41/commits/f897d6aab75fcd29bfa2ee455cef4595f2721600

**Review by Deewiant — APPROVED** [review]

**Comment by Deewiant** [comment]
Thanks, feel free to merge!
